name: Resize Image to 100x100 PNG

on:
  workflow_dispatch:
    inputs:
      image_url:
        description: 'Direct image URL (PNG/JPG)'
        required: true

jobs:
  resize:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install pillow

    - name: Download input image
      run: curl -L "${{ github.event.inputs.image_url }}" -o input.png

    - name: Run emoji resizer
      run: python resize.py

    - name: Upload resized image
      uses: actions/upload-artifact@v4
      with:
        name: resized-emoji
        path: emoji.png
